public class EYI_RECInventoryCreationWrapper {

        public List<cls_ImInput> IM_INPUT;

    // Constructor for the outer class (optional)
    public EYI_RECInventoryCreationWrapper() {
        this.IM_INPUT = new List<cls_ImInput>();  // Initialize inner class
    }
    
   
	public class cls_ImInput {
        public String Name;	//?
		public String MATNR;	//?
		public String MBRSH;	//?
		public String MTART;	//?
		public String MAKTX;	//?
		public String WERKS;	//?
		public String VKORG;	//?
		public String VTWEG;	//?
		public String MEINS;	//?
		public String MATKL;	//?
		public String EXTWG;	//?
		public String LABOR;	//?
		public String SPART;	//?
		public String MSTAE;	//?
		public String MTPOS;	//?
		public String BRGEW;	//?
		public String NTGEW;	//?
		public String GEWEI;	//?
		public String GAR_AREA;	//?
		public String TER_AREA;	//?
		public String BAL_AREA;	//?
		public String BUL_AREA;	//?
		public String COMM_AREA;	//?
		public String OPEN_AREA;	//?
		public String SITOUT_AREA;	//?
		public String VRV_AREA;	//?
		public String PLOBBY_AREA;	//?
		public String SERV_AREA;	//?
		public String ADJ_LOBBY_AREA;	//?
		public String PLOT_AREA;	//?
		public String VRKME;	//?
		public String DWERK;	//?
		public String MSTAV;	//?
		public String VALID_FROM;	//?
		public String TAX_CLASS;	//?
		public String TAX_CLASS_TCS;	//?
		public String ITEM_CAT;	//?
		public String VERSG;	//?
		public String KONDM;	//?
		public String KTGRM;	//?
		public String COMM_GRP;	//?
		public String MVGR1;	//?
		public String MVGR2;	//?
		public String MVGR3;	//?
		public String MVGR4;	//?
		public String MVGR5;	//?
		public String PRCTR;	//?
		public String HSNSAC;	//?
		public String TEXT;	//?
       
        
        
         // Constructor to initialize fields with default values
     public cls_ImInput() {
        this.MATNR = '';
        this.MBRSH = '';
        this.MTART = '';
        this.MAKTX = '';
        this.WERKS = '';
        this.VKORG = '';
        this.VTWEG = '';
        this.MEINS = '';
        this.MATKL = '';
        this.EXTWG = '';
        this.LABOR = '';
        this.SPART = '';
        this.MSTAE = '';
        this.MTPOS = '';
        this.BRGEW = '';
        this.NTGEW = '';
        this.GEWEI = '';
        this.GAR_AREA = '';
        this.TER_AREA = '';
        this.BAL_AREA = '';
        this.BUL_AREA = '';
        this.COMM_AREA = '';
        this.OPEN_AREA = '';
        this.SITOUT_AREA = '';
        this.VRV_AREA = '';
        this.PLOBBY_AREA = '';
        this.SERV_AREA = '';
        this.ADJ_LOBBY_AREA = '';
        this.PLOT_AREA = '';
        this.VRKME = '';
        this.DWERK = '';
        this.MSTAV = '';
        this.VALID_FROM = '';
        this.TAX_CLASS = '';
        this.TAX_CLASS_TCS = '';
        this.ITEM_CAT = '';
        this.VERSG = '';
        this.KONDM = '';
        this.KTGRM = '';
        this.COMM_GRP = '';
        this.MVGR1 = '';
        this.MVGR2 = '';
        this.MVGR3 = '';
        this.MVGR4 = '';
        this.MVGR5 = '';
        this.PRCTR = '';
        this.HSNSAC = '';
        this.TEXT = '';
    }
	}
    

}