global class EYI_PaymentReceitStatusWrapper {
    
      global List<PaymentWrapper> ReceiptStatus;
    
    
     global class PaymentWrapper{
        public	string	ReceivableDeskTrackingNumber;
        public	string	ReceivableDeskDocumentVersion;
        public	string	SapCompanyCode;
        public	string	HouseBank;
        public	string	AccountId;
        public	string	ShortKey;
        public	string	GlAccount;
        public	string	StatementNumber;
        public	string	MemoRecordNumber;
        public	string	StatementDate;
        public	string	BusinessTransCode;
        public	string	SapTransaction;
        public	string	BankPaymentConfirmationDate;
        public	decimal	PaymentConfirmedAmountFromSAP;
        //global	string	KWAER;
        public	string	AccountType;
        public	string	Account;
        public	string	SapDocumentNumber;
        public	string	FiscalYear;
        public	string	IsReversed;
        public	string	CompanyName;
        public	string	Reference;
        public	string	Assignment;
        public	string	Checknumber;
        public	string	DepartmentID;
        public	string	DepartmentName;
        public	string	Description;
        public	string	Site;
        public	string	SiteName;
        public	string	PaymentStatus;
        public	string	SapCustomerNumber;
        public	string	SapCustomerName;
        public	string	SapPaymentAdviceNumber;
        public	STRING	PDF;
        public	string	InitialRemark;
        public	string	AttachmentRemark;
        public	string	ChangeRemark;
        public	string	RecvDeskCreatedDate;
        public	string	RecvDeskCreatedBy;
        public	string	RecvDeskCreatedTime;
        public	string	RecvDeskChangedOn;
        public	string	RecvDeskChangedBy;
        public	string	RecvDeskChangedTime;
        public	string	AttachedOn;
        public	string	AttachedBy;
        public	string	AttachedAt;
        public	string	DmsDocType;
        public	string	DmsDocNo;
        public	string	DmsDocPart;
        public	string	RecvDeskProcessedDate;
        public	string	RecvDeskProcessedBy;
        public	string	RecvDeskProcessedTime;
        public	string	SapReasonCode;
        public	string	SapReasonDescription;
        public	string	SapRejectionHoldRemarks;
        public	string	DelayWRTCreation;
        public	string	SapBRSDocumentNumber;
        public	string	BankPostingDate;
        public	string	RecvDeskApprovedBy;
        public	string	RecvDeskApprovedDate;
        public	string	RecvDeskApprovedTime;
        public	string	RecvDeskCreatedByName;
        public	string	RecvDeskChangedByName;
        public	string	ProcessedBy;
        public	string	RecvDeskApprovedByName;
        
        
    }
    

}