/**
 * @Name: EYI_ProjectResponseWrapper
 * @Description: This is a wrapper class for Project creation API response.
 * @Author: *Add here*
 * @Creation Date: 14-Feb-2025
 * @Creation Date: 14-Feb-2025
 * @Version: 1
 * @Usage: This class should not be instantiated directly. It is called by the EYI_ProjectSyncToMobileApp.
 * @Example: 
 * @See: EYI_ProjectSyncToMobileApp
 * @Related: EYI_ProjectSyncToMobileApp
 * @Notes: 
**/
public class EYI_ProjectResponseWrapper {
	public String Id;
}